title: "Content Delivery"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/copy"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: troy
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  troy:
    name: troy
    display_name: troy
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
social:
  linkedin: https://linkedin.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
